# Generated by Django 3.0.5 on 2021-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='api/', verbose_name='Изображение публикации')),
            ],
        ),
    ]
