# Generated by Django 3.0.5 on 2021-02-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='year',
        ),
    ]
